"""Tests for G-code layer parser in kos_rewind."""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'tools'))

from kos_rewind import find_layer_position, apply_z_offset

# PrusaSlicer / OrcaSlicer style
SAMPLE_GCODE_PRUSA = """; generated by PrusaSlicer
M104 S210
G28
;BEFORE_LAYER_CHANGE
;10.0
G1 Z10.000 F600
;LAYER:50
G1 X100 Y100 F3000
G1 E1.5 F300
;BEFORE_LAYER_CHANGE
;10.2
G1 Z10.200 F600
;LAYER:51
G1 X110 Y110 F3000
"""

# Cura style
SAMPLE_GCODE_CURA = """;FLAVOR:Marlin
;Generated with Cura_SteamEngine
;LAYER:0
G1 Z0.3 F600
G1 X50 Y50 F3000
;LAYER:25
G1 Z5.0 F600
G1 X60 Y60 F3000
;LAYER:26
G1 Z5.2 F600
"""


class TestFindLayerPosition:
    def test_find_prusa_layer_by_comment(self):
        pos, z = find_layer_position(SAMPLE_GCODE_PRUSA, target_layer=50)
        assert pos is not None
        assert z == 10.0

    def test_find_prusa_layer_51(self):
        pos, z = find_layer_position(SAMPLE_GCODE_PRUSA, target_layer=51)
        assert pos is not None
        assert z == 10.2

    def test_find_layer_not_found(self):
        pos, z = find_layer_position(SAMPLE_GCODE_PRUSA, target_layer=999)
        assert pos is None
        assert z is None

    def test_find_cura_style(self):
        pos, z = find_layer_position(SAMPLE_GCODE_CURA, target_layer=25)
        assert pos is not None

    def test_find_cura_layer_0(self):
        pos, z = find_layer_position(SAMPLE_GCODE_CURA, target_layer=0)
        assert pos is not None


class TestApplyZOffset:
    def test_apply_positive_offset(self):
        lines = ["G1 Z10.000 F600", "G1 X100 Y100", "G1 Z10.200 F600"]
        result = apply_z_offset(lines, 1.0)
        assert "G1 Z11.000 F600" in result
        assert "G1 Z11.200 F600" in result
        assert "G1 X100 Y100" in result  # non-Z lines unchanged

    def test_zero_offset_no_change(self):
        lines = ["G1 Z10.000 F600"]
        result = apply_z_offset(lines, 0.0)
        assert result[0] == "G1 Z10.000 F600"
